"""
RENAME TO Config.py

Fill in the blanks PASS, IDENT, CHANNEL, WALLOFSHAMEFILE
"""

#Channel Information
HOST = "irc.twitch.tv"
PORT = 6667
# Password from http://www.twitchapps.com/tmi/ - looks like 'oauth:lfkhgaslkhfgki'
PASS = ""
IDENT = ""  # Name of bot
CHANNEL = "" # Channel that the bot will join

# Jelly Wall of Shame info
# .json file generated by Google Sheets API goes here
WALLOFSHAMEFILE = ''

# For Jelly Game: Use True/False here
# False = Jelly game picks 5 players at random
# True = Jelly game takes first 5 signups only
jellyGameTake5PlayersOnly = False
